{{- if .Values.fluentBitEnabled }}
{{- $dot := . -}}
{{- $default := $dot.Values.defaultFluentBit -}}
{{- range $i, $value := .Values.fluentBit }}
{{- $fluentBitName := printf "%s-%s" (include "fluent-sandbox.fullname" $dot) (ternary (printf "fluentd-bit-%d" $i) $value.name (empty $value.name)) -}}
{{- $imageRepository := (default $default.imageRepo $value.imageRepo) -}}
{{- $imageTag := (default $default.imageTag $value.imageTag) -}}
{{- $imagePullPolicy := (default $default.imagePullPolicy $value.imagePullPolicy) -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fluentBitName }}
  labels:
    {{- include "fluent-sandbox.labels" $dot | nindent 4 }}
spec:
  {{- with (default $default.ports $value.ports) }}
  ports:
    {{- range $name, $port := . }}
    - name: {{ $name }}
      port: {{ $port }}
    {{- end }}
  {{- end }}
  clusterIP: None
  selector:
    {{- include "fluent-sandbox.fluentBitAppLabels" $dot | nindent 4 }}
    {{- include "fluent-sandbox.selectorLabels" $dot | nindent 4 }}
    {{- include "fluent-sandbox.instanceSelectorLabels" $fluentBitName | nindent 4 }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $fluentBitName }}
  labels:
    {{- include "fluent-sandbox.fluentBitAppLabels" $dot | nindent 4 }}
    {{- include "fluent-sandbox.labels" $dot | nindent 4 }}
spec:
  serviceName: {{ $fluentBitName }}
  replicas: {{ default $default.replicas $value.replicas }}
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      {{- include "fluent-sandbox.fluentBitAppLabels" $dot | nindent 6 }}
      {{- include "fluent-sandbox.selectorLabels" $dot | nindent 6 }}
      {{- include "fluent-sandbox.instanceSelectorLabels" $fluentBitName | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ (default $default.conf $value.conf) | sha256sum }}
      {{- with (default $default.annotations $value.annotations) }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "fluent-sandbox.fluentBitAppLabels" $dot | nindent 8 }}
        {{- include "fluent-sandbox.selectorLabels" $dot | nindent 8 }}
        {{- include "fluent-sandbox.instanceSelectorLabels" $fluentBitName | nindent 8 }}
        {{- with (default $default.labels $value.labels) }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      restartPolicy: {{ default $default.restartPolicy $value.restartPolicy }}
      {{- with (default $default.imagePullSecrets $value.imagePullSecrets) }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (default $default.nodeSelector $value.nodeSelector) }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (default $default.affinity $value.affinity) }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (default $default.tolerations $value.tolerations) }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: fluent-bit-conf
          configMap:
            name: {{ $fluentBitName }}
        {{- with (default $default.volumes $value.volumes) }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      containers:
        - name: fluent-bit
          image: "{{ $imageRepository }}:{{ $imageTag }}"
          imagePullPolicy: {{ $imagePullPolicy }}
          securityContext:
            {{- toYaml (default $default.securityContext $value.securityContext) | nindent 12 }}
          {{- with (default $default.command $value.command) }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with (default $default.ports $value.ports) }}
          ports:
            {{- range $name, $port := . }}
            - name: {{ $name }}
              containerPort: {{ $port }}
            {{- end }}
          {{- end }}
          {{- with (default $default.livenessProbe $value.livenessProbe) }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with (default $default.readinessProbe $value.readinessProbe) }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with (default $default.startupProbe $value.startupProbe) }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: fluent-bit-conf
              mountPath: /fluent-bit/etc
              readOnly: true
            {{- with (default $default.volumeMounts $value.volumeMounts) }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fluentBitName }}
  labels:
    {{- include "fluent-sandbox.labels" $dot | nindent 4 }}
data:
  fluent-bit.yaml: |-
    {{- default $default.conf $value.conf | nindent 4 }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $fluentBitName }}
  annotations:
    "helm.sh/hook": post-upgrade,post-install
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    {{- include "fluent-sandbox.fluentBitAppLabels" $dot | nindent 4 }}
    {{- include "fluent-sandbox.labels" $dot | nindent 4 }}
spec:
  backoffLimit: 3
  template:
    metadata:
      {{- with (default $default.annotations $value.annotations) }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "fluent-sandbox.fluentBitAppLabels" $dot | nindent 8 }}
        {{- include "fluent-sandbox.labels" $dot | nindent 8 }}
        {{- with (default $default.labels $value.labels) }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      restartPolicy: Never
      {{- with (default $default.imagePullSecrets $value.imagePullSecrets) }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (default $default.nodeSelector $value.nodeSelector) }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (default $default.affinity $value.affinity) }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (default $default.tolerations $value.tolerations) }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: fluent-bit-conf
          configMap:
            name: {{ $fluentBitName }}
      containers:
        - name: dryrun
          image: "{{ $imageRepository }}:{{ $imageTag }}"
          imagePullPolicy: {{ $imagePullPolicy }}
          securityContext:
            {{- toYaml (default $default.securityContext $value.securityContext) | nindent 12 }}
          command:
            {{- toYaml (default $default.dryrunCommand $value.dryrunCommand) | nindent 12 }}
          volumeMounts:
            - name: fluent-bit-conf
              mountPath: /fluent-bit/etc
              readOnly: true
{{ end }}
{{- end }}
